name: al_bashaariy
description: AL BASHAARIY - A comprehensive Arabic library.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.
    sdk:sdk: ">=3.3.0 <4.0.0"
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_tts: ^4.2.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/poem_demo.mp3

  assets:
    - assets/poem_audio.wav
